const data = {
  products: [
    {
      name: 'toy 1',
      slug: 'toy-1',
      category: 'simple-toys',
      image: 'images/img1.jpeg',
      price: '₹120',
      countInStock: 10,
      rating: 4.9,
      numReviews: 10,
      description: 'simple toy to decor your home',
    },
    {
      name: 'toy 2',
      slug: 'toy-2',
      category: 'simple-toys',
      image: 'images/img2.jpeg',
      price: '₹130',
      countInStock: 10,
      rating: 4.9,
      numReviews: 10,
      description: 'simple toy to decor your home',
    },
    {
      name: 'toy 3',
      slug: 'toy-3',
      category: 'simple-toys',
      image: 'images/img3.jpeg',
      price: '₹100',
      countInStock: 10,
      rating: 4.9,
      numReviews: 10,
      description: 'simple toy to decor your home',
    },
    {
      name: 'toy 4',
      slug: 'toy-4',
      category: 'simple-toys',
      image: 'images/img4.jpeg',
      price: '₹120',
      countInStock: 10,
      rating: 4.9,
      numReviews: 10,
      description: 'simple toy to decor your home',
    },
    {
      name: 'toy 5',
      slug: 'toy-5',
      category: 'simple-toys',
      image: 'images/img5.jpeg',
      price: '₹190',
      countInStock: 10,
      rating: 4.9,
      numReviews: 10,
      description: 'simple toy to decor your home',
    },
    {
      name: 'toy 6',
      slug: 'toy-6',
      category: 'simple-toys',
      image: 'images/img6.jpeg',
      price: '₹150',
      countInStock: 10,
      rating: 4.9,
      numReviews: 10,
      description: 'simple toy to decor your home',
    },
  ],
};

export default data;
